### ISSUE TITLE
Pre-commit formatter seems to be broken

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#51]
**Describe the bug**
The pre-commit formatter seems not working.
Because of that, unnecessary changes are detected.

**Additional context**
Todo:
* Investigate if the formatted works or not
* If not, fix it
* If yes, list up other possibilities which cause this problem

**Comment by issmail-basel** [comment]
@HideBa , @KaWaite , I had the same issue, after investigating, I noticed the terminal was giving me the following warnings:
`'.husky/pre-commit' hook was ignored because it's not set as executable`
with some research I managed to fix this problem on my device by using the follwing:
```
chmod ug+x .husky/*
chmod ug+x .git/hooks/*
```
inspired by this [stackoverflow answer](https://stackoverflow.com/questions/8598639/why-is-my-git-pre-commit-hook-not-executable-by-default)
